version: "3.8"
services:
  db:
    image: postgres:12
    container_name: ict_pg
    environment:
      POSTGRES_DB: ict_meetup_v7
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ict_app
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ict_meetup_v7
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

volumes:
  progresDB:
